export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpeg",
      username: "Byun Baekhyun",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpeg",
      username: "Kim Jongin",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpeg",
      username: "Do Kyungsoo",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpeg",
      username: "Park Chanyeol",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpeg",
      username: "Lee Taemin",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpeg",
      username: "Joshua Hong",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpeg",
      username: "Yoon Jeonghan",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpeg",
      username: "Choi Soobin",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpeg",
      username: "Kang Seulgi",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpeg",
      username: "Irene",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "look at my dogieeeee🐶🐶",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      desc:"🥰",
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 29,
      comment: 14,
    },
    {
      id: 3,
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      desc:"feeling cute😈",
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      desc:"😺💖💖",
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      desc:"sunday morning sun is shining🌞",
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "by Joshua",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      desc:"nature",
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 45,
      comment: 11,
    },
    {
      id: 9,
      desc: "at the beach.🌈",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 118,
      comment: 80,
    },
    {
      id: 10,
      desc:"by Seulgi❤",
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 55,
    },
  ];